# netlify.toml

[build]
  command = "npm run build" 
  publish = "dist"        

[build.environment]
  VITE_ARROW_TRANSPORT = "suffix"

[[edge_functions]]
  function = "data-encoding"
  path = "/data/*"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-store, no-transform"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript" # Или "text/javascript" - оба валидны

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
